---
- name: "Install | Ensure directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "{{ '0750' if item == '/etc/vff-backup' else '0755' }}"
  loop:
    - /etc/vff-backup
    - "{{ restic_cache_dir }}"

- name: "Install | Ensure restic is installed (optional)"
  when: install_restic | bool
  ansible.builtin.package:
    name: restic
    state: present

- name: "Install | Ensure fuse3 is installed (optional)"
  when: install_fuse | bool
  ansible.builtin.package:
    name: fuse3
    state: present

- name: "Install | Ensure jq is installed (for JSON parsing)"
  when: install_jq | bool
  ansible.builtin.package:
    name: jq
    state: present

- name: "Install | Check restic availability (fail if missing and not installing)"
  when: not (install_restic | bool)
  ansible.builtin.command: bash -lc 'command -v restic'
  register: restic_cmd
  changed_when: false
  failed_when: restic_cmd.rc != 0
