---
# === S3 / Restic (секреты — НЕ в defaults) ===
backup_minio_endpoint: "https://s3.example.com"
backup_bucket: "vff-backups"
backup_s3_region: "us-east-1"
backup_restic_repository: ""   # задание в group_vars/<service>.yml

# секреты по умолчанию НЕ задаём
backup_restic_password: null
backup_aws_access_key_id: null
backup_aws_secret_access_key: null

# Метрики Prometheus textfile (node_exporter) — можно отключить
backup_enable_metrics: true

# Куда писать метрики (используется только если backup_enable_metrics=true)
backup_node_exporter_textfile_dirs:
  - /var/lib/node_exporter/textfile_collector

# Расписание таймеров (глобально для всех джобов этой роли)
backup_timer_oncalendar: "*-*-* 02:30:00"
backup_timer_randomized_delay: "900s"

# Retention (L7 / D14 / W8 / M12)
backup_forget_policy:
  keep_last: 7
  keep_daily: 14
  keep_weekly: 8
  keep_monthly: 12

# Скрипт + env (единообразно!)
backup_bin_path: /usr/local/bin/vff-backup.sh
backup_env_dir: /etc/vff-backup
backup_env_file: "{{ backup_env_dir }}/restic.env"

# Пути по умолчанию (могут переопределяться группами/хостами/джобом)
backup_compose_dir: /opt/shm
backup_db_dump_dir: /var/backups/db

backup_jobs: []

# Ротация локальных SQL-дампов (перед restic backup)
# Если >0 — оставлять только N последних файлов *.sql.gz в dump_dir
backup_dump_keep_count: 7
# Если >0 и backup_dump_keep_count == 0 — удалять старше N дней
backup_dump_keep_days: 0
